### PR TITLE
Use SONARCLOUD_TOKEN instead of SONAR_TOKEN

### PR DESCRIPTION
**Pull request by dlyash**
It's globally defined at the organizational level so should work for all repos OOTB. Currently, the workflow assumes you have the `SONAR_TOKEN` secret defined for your repo.

### CODE REVIEW

**Comment by OrenZiv** [comment]
Already tried that, it doesn't really work.

**Comment by dlyash** [comment]
Hmm, do you remember what didn't work for you?

B/c it runs w/o any issues for me: 

- https://github.com/IndependentIP/core-client-java/actions/runs/6509607155/job/17681456695#step:1:36
- https://github.com/IndependentIP/core-client-java/actions/runs/6509607155/job/17681456695#step:6:7

**Comment by OrenZiv** [comment]
I don't remember exactly, but it became kinda unreliable. 
Some projects worked, and some didn't, and since I didn't think becoming more granular with this is a bad idea anyway I didn't bother digging into it too much.

**Comment by dlyash** [comment]
Ok, I'll go ahead with copy-pasting tokens to all repositories, but honestly, this doesn't seem like a healthy solution.

**Comment by OrenZiv** [comment]
> Ok, I'll go ahead with copy-pasting tokens to all repositories, but honestly, this doesn't seem like a healthy solution.

I actually create a token per repo

**Comment by simi** [comment]
How do you pass secrets to shared workflows/action?

**Comment by OrenZiv** [comment]
> How do you pass secrets to shared workflows/action?

`secrets: inherit`

**Comment by dlyash** [comment]
> I actually create a token per repo

Isn't that one connected to your account? So when/if you leave FUGA all workflows will break?

**Comment by OrenZiv** [comment]
> > I actually create a token per repo
> 
> Isn't that one connected to your account? So when/if you leave FUGA all workflows will break? You probably see them under https://sonarcloud.io/account/security.
> 
> The one on the org level is linked to a service account which will never expire

I usually set it up as a part of the project in sonar cloud.
So inside the project, administration -> analysis method -> github actions

**Comment by dlyash** [comment]
Yeah, that's definitely connected to an account.

**Comment by OrenZiv** [comment]
> Yeah, that's definitely connected to your account.

Then we should definitely change that.

**Comment by OrenZiv** [comment]
BTW, I don't mind merging this change and see how it goes, just letting you know that there were problems with it in the past. 
Maybe we need to create a new org-level token(?) and that will fix this.

**Comment by dlyash** [comment]
What they say on the docs:
> Tokens are always linked to an account, but it does not have to be an account of some real person.
You can create a technical account on GitHub, managed by a group of people in your organization.

Yes, and I believe the `SONARCLOUD_TOKEN` is created like this. Probably bound to @FugaJenkins or @fugasysadmin, which, importantly, are service users.

**Comment by OrenZiv** [comment]
> What they say on the docs:
> 
> > Tokens are always linked to an account, but it does not have to be an account of some real person.
> > You can create a technical account on GitHub, managed by a group of people in your organization.
> 
> Yes, and I believe the `SONARCLOUD_TOKEN` is created like this. Probably bound to @FugaJenkins or @fugasysadmin, which, importantly, are service users.

Fine by me. Let's merge it then, we can always rollback if it creates problems.

**Review by OrenZiv — APPROVED** [review]

**Comment by dlyash** [comment]
Ah, wait.. weren't the issues related to @dependabot?

**Comment by OrenZiv** [comment]
> Ah, wait.. weren't the issues related to @dependabot?

Don't think so, Dependabot has it's own org-level token (called `SONAR_TOKEN`, so this will break it, but changing this is an easy fix...)

**Pull request merged**
